on:
  pull_request:

jobs:
  run-tests:
    name: Unit-Test Parser
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv export > requirements.txt && pip install -r requirements.txt

      - name: Run tests
        run: PYTHONPATH=. pytest
